### PR TITLE
Update PMP results

### PR DESCRIPTION
**Pull request by lee1043**
- Latest results of PCMDI Simulation Summary mirrored to CMEC
- Metrics results updated with newest models
- Directory structure re-organized under research/metrics for efficient maintenance on different versions
- (minor) broken link for ILAMB fixed

### CODE REVIEW

**Comment by lee1043** [comment]
@mauzey1 could you please help this update to be reflected on the CMEC website? Could you please remind me if I can just merge it to the master branch then it automatically goes to the web server, or is there any other branch that goes to the web server? Thank you.

**Comment by mauzey1** [comment]
@gleckler1 @lee1043 Currently, the `production` branch of this repo is being used by the web server for cmec.llnl.gov.  You could still merge your changes into `master` but we will need to merge `master` into `production` afterwards.

**Comment by durack1** [comment]
@lee1043 looking forward to seeing this, can you post the URL when it lands please?

**Review by mauzey1 — APPROVED** [review]

**Comment by lee1043** [comment]
@durack1 Please see https://cmec.llnl.gov/results/physical.html
@mauzey1 thank you for your help!

**Comment by lee1043** [comment]
@durack1 any feedback welcome!

**Comment by durack1** [comment]
@lee1043 just spotted that https://cmec.llnl.gov/research/metrics/enso/cmip5_6_enso_perf.html is dead when linked off https://cmec.llnl.gov/results/latest/enso/

**Comment by lee1043** [comment]
@durack1 great, thank you for finding it out! I will fix it.

**Comment by durack1** [comment]
@lee1043 same with https://cmec.llnl.gov/research/metrics/enso/cmip5_6_enso_tel.html, I'll keep clicking!

**Comment by durack1** [comment]
@lee1043 mjo links (https://cmec.llnl.gov/results/latest/mjo/) look good, and pretty!

**Comment by durack1** [comment]
@lee1043 https://cmec.llnl.gov/results/latest/monsoon/ also looks good

**Comment by durack1** [comment]
As does https://cmec.llnl.gov/results/latest/variability_modes

**Comment by durack1** [comment]
@lee1043 off https://cmec.llnl.gov/results/latest/mean_clim/ the PCMDIObs2 link would be better to use the raw json, so https://raw.githubusercontent.com/PCMDI/PCMDIobs-cmor-tables/master/catalogue/pcmdiobs2_clims_byVar_catalogue_v20200615.json rather than https://github.com/PCMDI/PCMDIobs-cmor-tables/blob/master/catalogue/pcmdiobs2_clims_byVar_catalogue_v20200615.json

This would then be directly machine readable

**Comment by lee1043** [comment]
@durack1 I pushed my revision accordingly. Many thanks for your clicking and comments for the json link!

**Comment by durack1** [comment]
@lee1043 https://cmec.llnl.gov/results/latest/enso/cmip5_6_enso_tel.html and https://cmec.llnl.gov/results/latest/enso/cmip5_6_enso_perf.html load for me now!

**Comment by lee1043** [comment]
@doutriaux1 thanks for confirming!

**Comment by doutriaux1** [comment]
> @doutriaux1 thanks for confirming!

@lee1043 what do you need?

**Comment by lee1043** [comment]
@doutriaux1 oops, meant @durack1, sorry for the typo!

**Pull request merged**
