### PR TITLE
Add analytics script for the DOE website audit

### PR DESCRIPTION
**Pull request by mauzey1**

### CODE REVIEW

**Comment by pochedls** [comment]
@mauzey1 - for this PR - would you like me to pull the code and test the functionality to see if I like the new feature(s)?

**Comment by mauzey1** [comment]
@pochedls Yes, please check if the changes impact the site.  Ideally, it shouldn't change the functionality of the site.

**Comment by pochedls** [comment]
> @pochedls Yes, please check if the changes impact the site. Ideally, it shouldn't change the functionality of the site.

Wait - this is for CMEC, not pcmdi.github.io, right? If this doesn't effect pcmdi.github.io, I think @lee1043 is probably a better reviewer.

**Comment by mauzey1** [comment]
@pochedls @lee1043 
The analytics script is meant for all of our public-facing websites including cmec.llnl.gov.

**Comment by pochedls** [comment]
> @pochedls @lee1043
> The analytics script is meant for all of our public-facing websites including cmec.llnl.gov.

Okay - if you add a PR to pcmdi.github.io I can review it. I don't think this PR will affect pcmdi.github.io.

**Comment by mauzey1** [comment]
@pochedls I have already added this script to pcmdi.github.io.  I will replace you with @lee1043 for review.

**Comment by lee1043** [comment]
Thanks for adding this, @mauzey1. I am approving it.

**Review by lee1043 — APPROVED** [review]

**Pull request merged**
